# Generated by Django 6.0.3 on 2026-04-06 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_banniere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='commentaires',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='news.article'),
        ),
    ]
